### ISSUE TITLE
"Reboot required" misreporting. Checked via CLI that server needs reboot, SysWard shows false.

### ISSUE THREAD

**Issue by etec-masterofsynapse** [sysward/sysward#34]

**Comment by joshrendek** [comment]
@etec-masterofsynapse which OS and version did this happen on?

**Comment by etec-masterofsynapse** [comment]
@joshrendek Both the SysWard server and the client are running Ubuntu 22.04 LTS, newest patch level.
And when I double-check if the server needs a restart, I look at /var/run/reboot-required.
That file exists, but SysWard still shows false.

**Comment by joshrendek** [comment]
Alright I'm able to reproduce this in our test environment - will let you know when an update is pushed.

**Comment by joshrendek** [comment]
Alright this is fixed in agent version: 2024081610426857713 and appliance version: 201808225384

**Comment by etec-masterofsynapse** [comment]
Can confirm, updated to newest version, and WebUI now shows some "true" for reboot required.
